Add outline of Swerve Robot
chopshop-166/frc-2022-swerve pull request #1
Opened 2021-08-19 00:04 UTC by bot190

Adds outline of code for 2020 swerve robot. This includes some initial swerve code, but it's still a ways away from functional.

2021-08-19 01:20 UTC, msoucy requested changes

2021-08-19 01:20 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +    final private NetworkTableEntry nameEntry = Shuffleboard.getTab("RobotData").addPersistent("RobotName", "Unknown")
We should switch to using MAC address instead of "robot name"

2021-08-19 01:20 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +    SwerveDriveKinematics kinematics;
Please make these private

2021-08-19 01:20 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +            SwerveModuleState rearRight = moduleStates[3];
Missing a step after this, I think

2021-08-19 01:20 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +        // Nothing to reset here
Should this reset the Gyro as well?

2021-08-19 01:20 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public void periodic() {
Why have these?

2021-08-19 01:33 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public void periodic() {
They're just leftover from `ExampleSubsystem.java`

2021-08-21 02:56 UTC, msoucy requested changes

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    private static final double GEAR_RATIO = 1 / 6.86;
Comment explaining where 6.86 comes from?

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    private static final double K_P = 0.1;
Will these be parameterized eventually?

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    private SwerveModuleState calculateSteeringAngle(final SwerveModuleState desiredState) {
Can this go at the bottom?

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    public static PIDSparkMax configureDriveMotor(final PIDSparkMax motor) {
Should this be called in the constructor?

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/robot/maps/RobotMap.java
> +        public SwerveModule frontLeft() {
If we're going to teach the "struct" approach this year, we should probably use it for this

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/robot/maps/SwerveBot.java
> +                return new SwerveModule(new Translation2d(MODULE_OFFSET_XY, MODULE_OFFSET_XY), new CANCoder(1),
Food for future thought - if the `MODULE_OFFSET_XY` is important, and we do the struct form of maps, and we abstract this... then we should be able to take care of this part in the constructor.

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +                () -> driveController.getY(Hand.kLeft), () -> driveController.getX(Hand.kLeft)));
Methinks you're going left when you should be going right

2021-08-21 02:56 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public CommandBase fieldCentricDrive(final DoubleSupplier translateX, final DoubleSupplier translateY,
Future: Might benefit from a second wrapper that takes an `XboxController` and just calls this with appropriate lambdas using it.

2021-08-21 03:11 UTC, bot190 commented on src/main/java/frc/outputs/SwerveModule.java
> +    private static final double K_P = 0.1;
These should be constant for the MK3 Swerve module. This could probably be refactored to better handle different swerve modules through subclassing or something.

2021-08-21 03:15 UTC, bot190 commented on src/main/java/frc/outputs/SwerveModule.java
> +    public static PIDSparkMax configureDriveMotor(final PIDSparkMax motor) {
In a guise of supporting other motor configurations SwerveModule takes `SmartMotorController` not `PIDSparkMax` so I can't call this in the constructor. I'm not sure if it's worth keeping that abstraction though.

2021-08-21 03:16 UTC, bot190 commented on src/main/java/frc/outputs/SwerveModule.java
> +    private SwerveModuleState calculateSteeringAngle(final SwerveModuleState desiredState) {
What about just before `configureDriveMotor()`?

2021-08-21 03:17 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    private SwerveModuleState calculateSteeringAngle(final SwerveModuleState desiredState) {
It's `private`, an implementation detail, so it seems to make sense to me to put it at the bottom

2021-08-21 03:17 UTC, msoucy commented on src/main/java/frc/outputs/SwerveModule.java
> +    private static final double K_P = 0.1;
Gotcha, we'll burn that bridge when we come to it then

2021-09-25 20:09 UTC, msoucy commented on src/main/java/frc/robot/maps/SwerveBot.java
> +        @Override
8 spaces?

2021-10-02 03:16 UTC, msoucy approved these changes

2021-10-02 03:16 UTC, merged