Integration work  as we bring up the swerve robot functionality
chopshop-166/frc-2022-swerve pull request #15
Opened 2021-10-25 04:09 UTC by bot190

Adds command mappings for basic functionality.
Some improvements in the other subsystems as well.

2021-10-26 00:47 UTC, msoucy requested changes

2021-11-02 00:53 UTC, msoucy requested changes

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        // driveController.getButton(Button.kX).whileHeld(shootPowerCell(shooterSpeeds.TrenchShot))
Commented out code

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        driveController.getPovButton(Direction.Left).whileHeld(intake.runIntake(false));
This and others - I hate boolean parameters, they don't really explain what they do.

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        // autoChooser.setDefaultOption("Initialize Systems", new
Commented code

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        autoChooser.addOption("Driveoff", drive.driveDistanceY(5));
Should use `addAutonomous`, but it's missing a default option... so not until it's fixed

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/maps/SwerveBot.java
> +        // return new TurretMap();
Commented code

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/maps/SwerveBot.java
> +        // return new ShooterMap();
Does our shooter not shoot?

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Kicker.java
> +        return new SequentialCommandGroup(new InstantCommand(() -> {
You can use `CommandRobot.sequence` to avoid needing `withName`, and `instant` instead of `new InstantCommand`

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Kicker.java
> +    public CommandBase runKicker(boolean up) {
Smurf naming

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Shooter.java
> +        // final PersistenceCheck rollerCheck = new PersistenceCheck(5,
Commented out stuff

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Spindexer.java
> +        // TODO Auto-generated method stub
`TODO`?

2021-11-02 00:53 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Turret.java
> +            return Math.abs(angle - encoder.getDistance()) <= POSITION_ERROR;
Get rid of the `return` and curly braces and it'll look prettier imo

2021-11-02 01:02 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Spindexer.java
> +        // TODO Auto-generated method stub
`TODONE`?

2021-11-03 20:21 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Kicker.java
> +        return new SequentialCommandGroup(new InstantCommand(() -> {
Created chopshop-166/chopshoplib#79 to add `sequence` and `parallel` to `SmartSubsystem` since they're missing for some reason.

2021-11-11 00:06 UTC, msoucy approved these changes

2021-11-11 00:06 UTC, merged